export enum CoreActionsEnum {
  CORE_GET_LANG = 'CORE_GET_LANG',
  CORE_SET_LANG = 'CORE_SET_LANG',

  CORE_SET_VISIBLE_MODAL = 'CORE_SET_VISIBLE_MODAL',
  CORE_REMOVE_VISIBLE_MODAL = 'CORE_REMOVE_VISIBLE_MODAL',

  CORE_GET_NEWS = 'CORE_GET_NEWS',
  CORE_SET_NEWS = 'CORE_SET_NEWS',

  CORE_GET_DOCS = 'CORE_GET_DOCS',
  CORE_SET_DOCS = 'CORE_SET_DOCS',

  CORE_SET_EMOTIONS = 'CORE_SET_EMOTIONS',
}
